// Исходное меню, перенесённое из menu.ps.me (Poster) 23.09.2026.
// Формат строки: [posterId, категория, цена ₾, ka, ru, en, порция?, фото из Poster?]
// Порция: "250 g", "0.5 L", "50 ml", "1 pcs" — на сайте единицы переводятся автоматически.
// После первого сохранения в админке меню живёт в базе данных, этот файл больше не используется.

export const POSTER_IMG = 'https://img.postershop.me/69e31c1f858c74b5c4edd91e/';

export const BAR_GROUPS = [
  { id: 'wine',      art: 'wine',      name: { ka: 'ღვინო', ru: 'Вино', en: 'Wine' } },
  { id: 'chacha',    art: 'chacha',    name: { ka: 'ჭაჭა', ru: 'Чача', en: 'Chacha' } },
  { id: 'brandy',    art: 'brandy',    name: { ka: 'კონიაკი და ბრენდი', ru: 'Коньяк и бренди', en: 'Cognac & brandy' } },
  { id: 'vodka',     art: 'vodka',     name: { ka: 'არაყი', ru: 'Водка', en: 'Vodka' } },
  { id: 'spirits',   art: 'spirits',   name: { ka: 'ვისკი და სხვა სასმელები', ru: 'Виски и крепкое', en: 'Whisky & spirits' } },
  { id: 'beer',      art: 'beer',      name: { ka: 'ლუდი', ru: 'Пиво', en: 'Beer' } },
  { id: 'cocktails', art: 'cocktails', name: { ka: 'კოქტეილები', ru: 'Коктейли', en: 'Cocktails' } },
  { id: 'coffee',    art: 'coffee',    name: { ka: 'ყავა და ჩაი', ru: 'Кофе и чай', en: 'Coffee & tea' } },
  { id: 'soft',      art: 'soft',      name: { ka: 'უალკოჰოლო სასმელები', ru: 'Безалкогольные напитки', en: 'Soft drinks' } },
];

// display: video — большая видео-карусель; compact — лёгкая лента без видео; list — список (бар)
export const CATEGORIES = [
  // ── КУХНЯ ──
  { id: 'cold',     section: 'kitchen', display: 'video',   steam: false, name: { ka: 'ცივი კერძები', ru: 'Холодные закуски', en: 'Cold appetizers' } },
  { id: 'salads',   section: 'kitchen', display: 'video',   steam: false, name: { ka: 'სალათები', ru: 'Салаты', en: 'Salads' } },
  { id: 'bakery',   section: 'kitchen', display: 'video',   steam: true,  name: { ka: 'ხაჭაპური და ცომეული', ru: 'Хачапури и выпечка', en: 'Khachapuri & bakery' } },
  { id: 'khinkali', section: 'kitchen', display: 'video',   steam: true,  name: { ka: 'ხინკალი', ru: 'Хинкали', en: 'Khinkali' } },
  { id: 'soups',    section: 'kitchen', display: 'video',   steam: true,  name: { ka: 'წვნიანები', ru: 'Супы', en: 'Soups' } },
  { id: 'hot',      section: 'kitchen', display: 'video',   steam: true,  name: { ka: 'ცხელი კერძები', ru: 'Горячие блюда', en: 'Hot dishes' } },
  { id: 'grill',    section: 'kitchen', display: 'video',   steam: true,  name: { ka: 'მაყალი', ru: 'Мангал', en: 'Charcoal grill' } },
  { id: 'fish',     section: 'kitchen', display: 'video',   steam: true,  name: { ka: 'თევზეული', ru: 'Рыба и икра', en: 'Fish & caviar' } },
  { id: 'sides',    section: 'kitchen', display: 'compact', steam: false, name: { ka: 'გარნირი', ru: 'Гарниры', en: 'Side dishes' } },
  { id: 'sauces',   section: 'kitchen', display: 'compact', steam: false, name: { ka: 'სოუსები', ru: 'Соусы и добавки', en: 'Sauces & extras' } },
  { id: 'desserts', section: 'kitchen', display: 'video',   steam: false, name: { ka: 'დესერტი', ru: 'Десерты', en: 'Desserts' } },
  // ── БАР ──
  { id: 'wine_tap',            section: 'bar', group: 'wine', name: { ka: 'ჩამოსასხმელი ღვინო', ru: 'Домашнее вино (разливное)', en: 'House wine (by the carafe)' } },
  { id: 'wine_sparkling',      section: 'bar', group: 'wine', name: { ka: 'ცქრიალა ღვინო', ru: 'Игристое вино', en: 'Sparkling wine' } },
  { id: 'wine_white_dry',      section: 'bar', group: 'wine', name: { ka: 'თეთრი მშრალი', ru: 'Белое сухое', en: 'White dry' } },
  { id: 'wine_white_semidry',  section: 'bar', group: 'wine', name: { ka: 'თეთრი ნახევრადმშრალი', ru: 'Белое полусухое', en: 'White semi-dry' } },
  { id: 'wine_white_semisweet',section: 'bar', group: 'wine', name: { ka: 'თეთრი ნახევრადტკბილი', ru: 'Белое полусладкое', en: 'White semi-sweet' } },
  { id: 'wine_amber',          section: 'bar', group: 'wine', name: { ka: 'ქარვისფერი', ru: 'Янтарное (квеври)', en: 'Amber (qvevri)' } },
  { id: 'wine_red_dry',        section: 'bar', group: 'wine', name: { ka: 'წითელი მშრალი', ru: 'Красное сухое', en: 'Red dry' } },
  { id: 'wine_red_semidry',    section: 'bar', group: 'wine', name: { ka: 'წითელი ნახევრადმშრალი', ru: 'Красное полусухое', en: 'Red semi-dry' } },
  { id: 'wine_red_semisweet',  section: 'bar', group: 'wine', name: { ka: 'წითელი ნახევრადტკბილი', ru: 'Красное полусладкое', en: 'Red semi-sweet' } },
  { id: 'wine_bottle',         section: 'bar', group: 'wine', name: { ka: 'ბოთლის ღვინო', ru: 'Вино в бутылках', en: 'Bottled wine' } },
  { id: 'chacha_tap',    section: 'bar', group: 'chacha',    name: { ka: 'ჩამოსასხმელი ჭაჭა', ru: 'Чача по бокалам', en: 'Chacha by the glass' } },
  { id: 'chacha_bottle', section: 'bar', group: 'chacha',    name: { ka: 'ბოთლის ჭაჭა', ru: 'Чача в бутылках', en: 'Bottled chacha' } },
  { id: 'brandy',        section: 'bar', group: 'brandy',    name: { ka: 'კონიაკი და ბრენდი', ru: 'Коньяк и бренди', en: 'Cognac & brandy' } },
  { id: 'vodka',         section: 'bar', group: 'vodka',     name: { ka: 'არაყი', ru: 'Водка', en: 'Vodka' } },
  { id: 'whisky',        section: 'bar', group: 'spirits',   name: { ka: 'ვისკი', ru: 'Виски', en: 'Whisky' } },
  { id: 'rum_tequila',   section: 'bar', group: 'spirits',   name: { ka: 'რომი, ტეკილა, ჯინი', ru: 'Ром, текила, джин', en: 'Rum, tequila, gin' } },
  { id: 'liqueurs',      section: 'bar', group: 'spirits',   name: { ka: 'ლიქიორი და ვერმუტი', ru: 'Ликёры и вермуты', en: 'Liqueurs & vermouth' } },
  { id: 'beer',          section: 'bar', group: 'beer',      name: { ka: 'ლუდი', ru: 'Пиво', en: 'Beer' } },
  { id: 'cocktails',     section: 'bar', group: 'cocktails', name: { ka: 'კოქტეილები', ru: 'Коктейли', en: 'Cocktails' } },
  { id: 'coffee',        section: 'bar', group: 'coffee',    name: { ka: 'ყავა და ჩაი', ru: 'Кофе и чай', en: 'Coffee & tea' } },
  { id: 'soft',          section: 'bar', group: 'soft',      name: { ka: 'გამაგრილებელი სასმელები', ru: 'Лимонады, соки, вода', en: 'Lemonades, juices, water' } },
  { id: 'milkshakes',    section: 'bar', group: 'soft',      name: { ka: 'მილქშეიქი', ru: 'Милкшейки', en: 'Milkshakes' } },
];

export const ROWS = [
  // ── Холодные закуски ──
  [29, 'cold', 18, 'იმერული ყველი', 'Имеретинский сыр', 'Imeretian cheese', '', '849e4513-987a-49d6-9568-c2cf1a7b6cb5-image.png'],
  [30, 'cold', 21, 'სულგუნი', 'Сулугуни', 'Sulguni cheese', '', '5eb8d7b4-1b44-419a-b309-e141bb038781-image.png'],
  [31, 'cold', 19, 'შებოლილი სულგუნი', 'Копчёный сулугуни', 'Smoked sulguni', ''],
  [28, 'cold', 24, 'ყველის ასორტი (იმერული, სულგუნი)', 'Сырное ассорти (сулугуни, имеретинский)', 'Assorted cheeses (sulguni, Imeretian)', '', 'caea68e8-3209-476b-aef4-3c0fafeee479-image.png'],
  [27, 'cold', 31, 'ყველის ასორტი (შებოლილი სულგუნი, იმერული, სულგუნი)', 'Сырное ассорти (сулугуни, имеретинский, копчёный сулугуни)', 'Assorted cheeses (sulguni, Imeretian, smoked sulguni)', '', 'b06faea9-23b6-4032-bc64-8abf1770e0e6-image.png'],
  [505, 'cold', 49, 'ყველის დაფა', 'Сырная доска', 'Cheese board', ''],
  [19, 'cold', 35, 'ფხალის ასორტი', 'Ассорти пхали', 'Assorted pkhali', '', '0181bdb4-8399-4c59-889c-15b505bc1005-image.png'],
  [21, 'cold', 16, 'ისპანახი ნიგვზით', 'Шпинат с орехами', 'Spinach pkhali with walnuts', '', '144758b5-22d4-4706-b045-2d38467c7d29-image.jpeg'],
  [22, 'cold', 16, 'წითელი ფხალი ნიგვზით', 'Пхали из свёклы с орехами', 'Beetroot pkhali with walnuts', '', '539678b3-2c9b-4f5c-8991-b978925ade9f-image.png'],
  [20, 'cold', 18, 'ბადრიჯანი ნიგვზით', 'Рулетики из баклажанов с орехами', 'Eggplant rolls with walnuts', '', '262e4d29-2b45-4cd4-9241-5103239e21a1-image.jpeg'],
  [331, 'cold', 14, 'ბადრიჯანი ნიორით', 'Баклажаны с чесноком', 'Eggplant with garlic', ''],
  [25, 'cold', 13.5, 'აჯაფსანდალი', 'Аджапсандали', 'Ajapsandali', '', '23079ed9-e414-4e66-9aec-ef17914db0c7-image.png'],
  [44, 'cold', 23, 'კუჭმაჭი ნიგვზით', 'Кучмачи с орехами', 'Kuchmachi with walnuts', '', '906e768a-2973-4e11-8a3d-9a3286acf834-image.jpeg'],
  [32, 'cold', 17, 'ნადუღი სულგუნის ფირფიტებში', 'Надуги в пластах сулугуни', 'Nadughi wrapped in sulguni', '', '1d1193a3-fd98-4678-82f2-be499e44715a-image.png'],
  [33, 'cold', 10.5, 'ნადუღი პიტნით', 'Надуги с мятой', 'Nadughi with mint', ''],
  [34, 'cold', 28, 'გებჟალია', 'Гебжалия', 'Gebzhalia', ''],
  [38, 'cold', 19.5, 'მოხარშული საქონლის ენა', 'Отварной говяжий язык', 'Boiled beef tongue', ''],
  [37, 'cold', 29, 'მოხარშული ბურვაკი', 'Отварная свинина', 'Boiled pork', ''],
  [40, 'cold', 36, 'შემწვარი ტაბაკა', 'Цыплёнок табака', 'Chicken tabaka', '', '65fd5a8f-89d8-4e82-ac2e-df534b06640e-image.png'],
  [43, 'cold', 34, 'წიწილი მაყვლის სოუსით', 'Цыплёнок в ежевичном соусе', 'Chicken in blackberry sauce', ''],
  [18, 'cold', 19, 'მჟავეს ასორტი', 'Ассорти соленьев', 'Assorted pickles', '', '5bed146a-b1f2-4f45-91dd-a586516ea1af-image.png'],
  [15, 'cold', 19, 'ბოსტნეულის ბაღჩა', 'Овощной букет', 'Fresh vegetable platter', '', 'd2bb532a-8ae3-4367-b1ae-c30723d48f02-image.png'],
  [16, 'cold', 15, 'მწვანილის ასორტი', 'Ассорти зелени', 'Assorted fresh herbs', ''],
  [17, 'cold', 14, 'ზეთისხილი', 'Маслины и оливки', 'Olives', ''],
  [444, 'cold', 4, 'კარაქი', 'Сливочное масло', 'Butter', ''],
  [484, 'cold', 5, 'თაფლი', 'Мёд', 'Honey', ''],

  // ── Салаты ──
  [6, 'salads', 17, 'კიტრი-პომიდვრის სალათი', 'Салат по-грузински', 'Cucumber & tomato salad', '', '1bacf6d4-5e6f-4f66-8b6d-e685bbec0d7a-image.jpeg'],
  [7, 'salads', 19, 'კიტრი-პომიდვრის სალათი ნიგვზით', 'Салат по-грузински с орехами', 'Cucumber & tomato salad with walnuts', ''],
  [10, 'salads', 15, 'მწვანე სალათი', 'Зелёный салат', 'Green salad', ''],
  [11, 'salads', 26, 'ბერძნული სალათი', 'Греческий салат', 'Greek salad', '', '00fbd920-0216-4348-b0f6-d2a42f1c6e49-image.jpeg'],
  [12, 'salads', 32, 'ცეზარი ქათმით', 'Цезарь с курицей', 'Caesar with chicken', '', '93eb5074-4c28-48be-b100-169c5d4019b9-image.png'],
  [14, 'salads', 32, 'ცეზარი კრევეტებით', 'Цезарь с креветками', 'Caesar with shrimp', '', 'ecc13a12-fbde-4ce3-85a3-aaa0aafb6cd6-image.png'],
  [13, 'salads', 41, 'ცეზარი ორაგულით', 'Цезарь с сёмгой', 'Caesar with salmon', ''],
  [8, 'salads', 17, 'ქათმის სალათი', 'Куриный салат', 'Chicken salad', '', 'a82f8f37-2dae-4268-bdc3-56201248766d-image.jpeg'],
  [402, 'salads', 31, 'ხრაშუნა ბადრიჯნის სალათი', 'Салат с хрустящими баклажанами', 'Crispy eggplant salad', '', '483b066d-ed6b-4461-bc5a-8a72d62c683b-image.jpeg'],
  [409, 'salads', 29, 'ჭარხლის სალათი თხის ყველით', 'Салат из свёклы с козьим сыром', 'Beetroot salad with goat cheese', '', 'bcb0b694-f7f2-4916-83c6-9f1fb8126217-image.png'],

  // ── Хачапури и выпечка ──
  [97, 'bakery', 22, 'იმერული ხაჭაპური', 'Хачапури по-имеретински', 'Imeretian khachapuri', '', 'ec53ed57-35f2-4db8-a840-e1b4322da3c2-image.png'],
  [296, 'bakery', 27, 'მეგრული ხაჭაპური', 'Хачапури по-мегрельски', 'Megrelian khachapuri', '', 'e507036d-7126-4775-b3e2-6d5343cec31b-image.png'],
  [99, 'bakery', 23, 'აჭარული ხაჭაპური', 'Хачапури по-аджарски', 'Adjarian khachapuri', '', '639d229e-c4ef-4678-9c1e-28bf7d1f0d58-image.png'],
  [96, 'bakery', 33.5, 'ხაჭაპური „სამეფო“', 'Хачапури «Царский»', 'Royal khachapuri', '', 'ae71c40d-8c39-4f5f-9c0a-f0a3fc1fadee-image.png'],
  [100, 'bakery', 24, 'ხაჭაპური შამფურზე', 'Хачапури на шампуре', 'Khachapuri on a skewer', '', '28255dd6-c85b-4c30-a279-61be59ffa9b3-image.jpeg'],
  [102, 'bakery', 16, 'ლობიანი', 'Лобиани', 'Lobiani', '', '0e013ff7-5e2b-4f6e-99f0-e84aba149c7e-image.png'],
  [112, 'bakery', 25, 'პიცა მარგარიტა', 'Пицца «Маргарита»', 'Pizza Margherita', ''],
  [113, 'bakery', 31, 'პიცა პეპერონი', 'Пицца «Пепперони»', 'Pepperoni pizza', '', '04f396ea-ed45-4f4a-83cf-d5c5914c4bf4-image.jpeg'],
  [103, 'bakery', 17, 'ბლინი ხორცით', 'Блинчики с мясом', 'Crêpes with meat', '', '7aee4de1-3f9b-417e-8b31-3e8c63b35570-image.png'],
  [104, 'bakery', 17, 'ბლინი სოკოთი', 'Блинчики с грибами', 'Crêpes with mushrooms', ''],
  [106, 'bakery', 17, 'ბლინი ყველით', 'Блинчики с сыром', 'Crêpes with cheese', ''],
  [109, 'bakery', 9, 'ჭვიშტარი', 'Чвиштари', 'Chvishtari', ''],
  [108, 'bakery', 4, 'მჭადი', 'Мчади', 'Mchadi (corn bread)', ''],
  [107, 'bakery', 3, 'ჩვენი პური', 'Наш хлеб', 'Our bread', ''],

  // ── Хинкали ── (цена за 1 шт.)
  [114, 'khinkali', 2.7, 'თბილისური ხინკალი', 'Хинкали по-тбилисски', 'Tbilisi khinkali', '1 pcs'],
  [115, 'khinkali', 2.7, 'მთიულური ხინკალი', 'Хинкали по-мтиульски', 'Mtiuluri khinkali', '1 pcs'],
  [116, 'khinkali', 3, 'ხინკალი საქონლის ხორცით', 'Хинкали с говядиной', 'Beef khinkali', '1 pcs'],
  [117, 'khinkali', 2.7, 'ხინკალი ყველით', 'Хинкали с сыром', 'Cheese khinkali', '1 pcs'],
  [118, 'khinkali', 2.6, 'ხინკალი სოკოთი', 'Хинкали с грибами', 'Mushroom khinkali', '1 pcs'],
  [119, 'khinkali', 2, 'ხინკალი კარტოფილით', 'Хинкали с картофелем', 'Potato khinkali', '1 pcs'],
  [430, 'khinkali', 29, 'თბილისური ხინკალი შქმერულ სოუსში', 'Хинкали по-тбилисски в шкмерском соусе', 'Tbilisi khinkali in shkmeruli sauce', '', 'feae7f6e-cf9f-44c2-b71b-0504d6c4fdbb-image.jpeg'],
  [504, 'khinkali', 28, 'თბილისური ხინკალი ტომატის სოუსში', 'Хинкали по-тбилисски в томатном соусе', 'Tbilisi khinkali in tomato sauce', ''],

  // ── Супы ──
  [81, 'soups', 24, 'სუპი ხარჩო', 'Суп харчо', 'Kharcho soup', ''],
  [229, 'soups', 19, 'ჩიხირთმა', 'Чихиртма', 'Chikhirtma', ''],
  [82, 'soups', 24, 'თათარიახლი', 'Татариахли', 'Tatariakhli', ''],
  [83, 'soups', 23, 'სოკოს კრემ-სუპი', 'Грибной крем-суп', 'Mushroom cream soup', ''],

  // ── Горячие блюда ──
  [59, 'hot', 36, 'ოჯახური ხბოს ხორცით', 'Оджахури из телятины', 'Ojakhuri with veal', '', '3f3b1b07-a0f9-4f61-8ffa-ccd1ec0d552b-image.png'],
  [60, 'hot', 25, 'ოჯახური ღორის ხორცით', 'Оджахури из свинины', 'Ojakhuri with pork', '', '35782042-8909-4998-8f59-8f07e32d51fb-image.jpeg'],
  [58, 'hot', 44, 'ხბოს ნეკნი აჯიკით', 'Телячьи рёбрышки с аджикой', 'Veal ribs with adjika', '', 'c480bc35-260b-43b9-b897-bda5a5421ff9-image.jpeg'],
  [63, 'hot', 44, 'საქონლის ოსტრი', 'Остри из говядины', 'Beef ostri', '', '48709a50-c82b-4c10-91f1-cb228237a995-image.png'],
  [64, 'hot', 59, 'საქონლის ხაშლამა', 'Хашлама из говядины', 'Beef khashlama', '', 'fc3f16de-27a9-4b55-b7fc-01e38ab44c30-image.png'],
  [66, 'hot', 21, 'ტოლმა ვაზის ფოთოლში', 'Толма в виноградных листьях', 'Tolma in vine leaves', '', '1ccb8afe-9b07-4a15-9b6a-aff63a9562e2-image.png'],
  [68, 'hot', 26.5, 'მეგრული კუპატი', 'Купаты по-мегрельски', 'Megrelian kupati', '', 'dbc1cd54-bb78-4243-92a3-b33e14faf135-image.png'],
  [67, 'hot', 25.5, 'იმერული კუპატი', 'Купаты по-имеретински', 'Imeretian kupati', ''],
  [69, 'hot', 26, 'აფხაზურა', 'Абхазура', 'Apkhazura', ''],
  [70, 'hot', 31, 'კუპატი და აფხაზურა', 'Купаты и абхазура', 'Kupati & apkhazura', '', 'b458ac33-c210-441c-81fc-972ef730bafa-image.png'],
  [71, 'hot', 28, 'მეგრული კუჭმაჭი', 'Кучмачи по-мегрельски', 'Megrelian kuchmachi', '', '31002fc8-d718-4cac-9d00-365ee603f025-image.png'],
  [74, 'hot', 18, 'ქამა სოკო კეცზე', 'Грибы на кеци', 'Mushrooms baked in ketsi', '', '5ae09887-ce23-449c-a45f-3b2a9305bc93-image.png'],
  [75, 'hot', 21, 'ქამა სოკო კეცზე სულგუნით', 'Грибы на кеци с сулугуни', 'Mushrooms in ketsi with sulguni', ''],
  [553, 'hot', 45, 'მწყერი (3 ცალი)', 'Перепела (3 шт.)', 'Quail (3 pcs)', '', '4faf7514-eb0a-4bc9-81eb-fe7199d1abee-image.png'],
  [93, 'hot', 17, 'შემწვარი მწყერი', 'Жареный перепел', 'Roasted quail', ''],
  [65, 'hot', 55, 'წიწილი შქმერულად', 'Цыплёнок по-шкмерски', 'Chicken shkmeruli', ''],
  [56, 'hot', 39.5, 'ხბოს ჩაქაფული', 'Чакапули из телятины', 'Veal chakapuli', ''],
  [55, 'hot', 34, 'ხბოს ჩაშუშული', 'Чашушули из телятины', 'Veal chashushuli', ''],
  [389, 'hot', 44, 'ნიგვზიანი ხარჩო', 'Харчо с орехами', 'Walnut kharcho', ''],
  [73, 'hot', 32, 'მადამ ბოვარი', '«Мадам Бовари»', 'Madame Bovary', ''],
  [78, 'hot', 24, 'მადამ ბოვარი (სამარხვო)', '«Мадам Бовари» (постное)', 'Madame Bovary (lenten)', ''],
  [72, 'hot', 21, 'ქათმის გულ-ღვიძლი', 'Куриные сердечки и печень', 'Chicken hearts & liver', ''],
  [77, 'hot', 19, 'სოკოს ოჯახური', 'Оджахури с грибами', 'Mushroom ojakhuri', ''],
  [76, 'hot', 19, 'სოკოს ჩაშუშული', 'Чашушули из грибов', 'Mushroom chashushuli', ''],
  [79, 'hot', 16, 'ლობიო ქოთანში', 'Лобио в горшочке', 'Lobio in a clay pot', ''],
  [230, 'hot', 20, 'ჩიჟი-პიჟი', 'Чижи-пижи', 'Chizhi-pizhi', ''],
  [111, 'hot', 15, 'ელარჯი', 'Эларджи', 'Elarji', ''],
  [110, 'hot', 8, 'ღომი', 'Гоми', 'Ghomi', ''],

  // ── Мангал ──
  [85, 'grill', 23, 'ღორის მწვადი', 'Шашлык из свинины', 'Pork mtsvadi', ''],
  [86, 'grill', 24, 'ღორის ნეკნის მწვადი', 'Шашлык из свиных рёбрышек', 'Pork rib mtsvadi', ''],
  [88, 'grill', 37, 'ხბოს მწვადი', 'Шашлык из телятины', 'Veal mtsvadi', ''],
  [87, 'grill', 19, 'ქათმის მწვადი', 'Шашлык из курицы', 'Chicken mtsvadi', ''],
  [90, 'grill', 59.5, 'ორაგულის მწვადი', 'Шашлык из сёмги', 'Salmon mtsvadi', ''],
  [92, 'grill', 22, 'ბოსტნეულის მწვადი', 'Овощи на мангале', 'Grilled vegetables', ''],
  [234, 'grill', 172.5, 'მწვადის ასორტი', 'Ассорти шашлыков', 'Assorted mtsvadi', ''],
  [94, 'grill', 21, 'შერეული ქაბაბი', 'Люля-кебаб смешанный', 'Mixed kebab', ''],
  [95, 'grill', 17, 'ქათმის ქაბაბი', 'Люля-кебаб из курицы', 'Chicken kebab', ''],
  [237, 'grill', 35, 'ქაბაბი სულგუნით', 'Люля-кебаб с сулугуни', 'Kebab with sulguni', ''],
  [575, 'grill', 24, 'ხბოს ღვიძლი ბადე ქონში', 'Телячья печень в сальнике', 'Veal liver in caul fat', ''],

  // ── Рыба и икра ──
  [51, 'fish', 23, 'შემწვარი კალმახი', 'Жареная форель', 'Fried trout', '', '533e09f0-0c52-4804-b4b9-de2a4cbc1308-image.png'],
  [52, 'fish', 22.5, 'შემწვარი კალმახი ბროწეულის სოუსით', 'Жареная форель под гранатовым соусом', 'Fried trout with pomegranate sauce', ''],
  [50, 'fish', 45, 'ორაგული ქინძმარში', 'Лосось в кинзмари', 'Salmon in kindzmari sauce', ''],
  [332, 'fish', 47, 'ლოქო ქინძმარში', 'Сом в кинзмари', 'Catfish in kindzmari sauce', ''],
  [388, 'fish', 51, 'ორაგული ბაჟეში', 'Лосось в соусе баже', 'Salmon in bazhe sauce', ''],
  [47, 'fish', 45, 'მსუბუქად დამარილებული ორაგული', 'Слабосолёный лосось', 'Lightly salted salmon', '', '158acf61-54c2-4d14-b0d7-c9b171ec8050-image.png'],
  [46, 'fish', 35.5, 'წითელი ხიზილალა', 'Красная икра', 'Red caviar', '', '5a8b528f-c508-4739-b80e-cbf62c8b6095-image.png'],

  // ── Гарниры ──
  [121, 'sides', 12, 'კარტოფილი ფრი', 'Картофель фри', 'French fries', '', '9f33f890-0964-4f22-a13c-a313d0796dc6-image.jpeg'],
  [80, 'sides', 15, 'კარტოფილი ოჯახურად', 'Картофель по-домашнему', 'Home-style potatoes', '', '8db0a1d2-775c-4cb8-a6bb-79fb22d5b0ce-image.jpeg'],
  [120, 'sides', 18, 'კარტოფილი მექსიკურად', 'Картофель по-мексикански', 'Mexican-style potatoes', '', '30d100f4-914c-444f-b6f4-b5e92ee70726-image.png'],
  [122, 'sides', 6, 'მოხარშული კარტოფილი', 'Отварной картофель', 'Boiled potatoes', ''],
  [125, 'sides', 12, 'ბრინჯი ბოსტნეულით', 'Рис с овощами', 'Rice with vegetables', ''],
  [124, 'sides', 5, 'მოხარშული ბრინჯი', 'Отварной рис', 'Boiled rice', ''],
  [437, 'sides', 16, 'ხახვის რგოლები', 'Луковые кольца', 'Onion rings', ''],
  [438, 'sides', 14, 'კალმარის რგოლები', 'Кольца кальмара', 'Calamari rings', ''],
  [360, 'sides', 2, 'მწვანე წიწაკა', 'Зелёный перец', 'Green chili pepper', ''],

  // ── Соусы и добавки ──
  [127, 'sauces', 4, 'ტყემალი', 'Ткемали', 'Tkemali', ''],
  [128, 'sauces', 4, 'პომიდვრის საწებელი', 'Томатный сацебели', 'Tomato satsebeli', ''],
  [131, 'sauces', 6, 'წითელი აჯიკა', 'Красная аджика', 'Red adjika', ''],
  [126, 'sauces', 12, 'ბაჟე', 'Баже', 'Bazhe (walnut sauce)', ''],
  [130, 'sauces', 5, 'ნაშარაფი', 'Наршараб', 'Narsharab (pomegranate sauce)', ''],
  [248, 'sauces', 3, 'კახური ზეთი', 'Кахетинское масло', 'Kakhetian oil', ''],
  [350, 'sauces', 4, 'არაჟანი', 'Сметана', 'Sour cream', ''],
  [495, 'sauces', 4, 'ერბო', 'Топлёное масло (эрбо)', 'Ghee (erbo)', ''],
  [361, 'sauces', 2, 'ნიორწყალი', 'Чесночная вода', 'Garlic water', ''],
  [362, 'sauces', 2, 'ძმარი', 'Уксус', 'Vinegar', ''],
  [129, 'sauces', 4, 'კეტჩუპი', 'Кетчуп', 'Ketchup', ''],
  [574, 'sauces', 4, 'მაიონეზი', 'Майонез', 'Mayonnaise', ''],

  // ── Десерты ──
  [415, 'desserts', 16, 'თაფლის ნამცხვარი', 'Медовик', 'Honey cake', '', '8423c150-45ee-432e-b0e8-32c979e5b74f-image.jpeg'],
  [412, 'desserts', 19, 'ალუბალი', 'Вишнёвый десерт', 'Cherry dessert', '', '0533559e-b37c-478c-8449-9b81ec42be35-image.jpeg'],
  [138, 'desserts', 15, 'ნაყინი', 'Мороженое', 'Ice cream', ''],
  [133, 'desserts', 25, 'საზამთრო და ნესვი', 'Арбуз и дыня', 'Watermelon & melon', '', 'fe0bb323-9995-4f09-961c-8bc367fbf256-image.png'],
  [132, 'desserts', 34, 'ხილის ასორტი', 'Фруктовое ассорти', 'Assorted fruit', ''],

  // ═════════ БАР ═════════
  // Разливное вино
  [158, 'wine_tap', 19, 'საფერავი', 'Саперави', 'Saperavi', '1 L'],
  [289, 'wine_tap', 7, 'საფერავი', 'Саперави', 'Saperavi', '250 ml'],
  [157, 'wine_tap', 16, 'რქაწითელი', 'Ркацители', 'Rkatsiteli', '1 L'],
  [366, 'wine_tap', 6, 'რქაწითელი', 'Ркацители', 'Rkatsiteli', '150 ml'],
  [156, 'wine_tap', 16.5, 'ევროპული', 'Европейское', 'European style', '1 L'],
  [335, 'wine_tap', 6, 'ევროპული', 'Европейское', 'European style', '150 ml'],
  // Игристое
  [206, 'wine_sparkling', 40, 'ცქრიალა „ბაგრატიონი“', 'Игристое «Багратиони»', 'Bagrationi sparkling', ''],
  [207, 'wine_sparkling', 35, 'ცქრიალა „მუხრანი“', 'Игристое «Мухрани»', 'Mukhrani sparkling', ''],
  [494, 'wine_sparkling', 37, 'ბრუტი „მაესტრო“', 'Брют «Маэстро»', 'Maestro brut', ''],
  // Белое сухое
  [376, 'wine_white_dry', 29, 'წინანდალი „ბადაგონი“', 'Цинандали «Бадагони»', 'Tsinandali “Badagoni”', ''],
  [306, 'wine_white_dry', 42, 'წინანდალი „მილდიანი“', 'Цинандали «Милдиани»', 'Tsinandali “Mildiani”', ''],
  [304, 'wine_white_dry', 32, 'რქაწითელი „მილდიანი“', 'Ркацители «Милдиани»', 'Rkatsiteli “Mildiani”', ''],
  [211, 'wine_white_dry', 35, 'რქაწითელი „დუგლაძე“', 'Ркацители «Дугладзе»', 'Rkatsiteli “Dugladze”', ''],
  [525, 'wine_white_dry', 64, 'რქაწითელი ქვევრის „ტერა“ 2021', 'Ркацители квеври «Тера» 2021', 'Rkatsiteli Qvevri “Tera” 2021', ''],
  [208, 'wine_white_dry', 34, 'კრახუნა „ჩელთი“', 'Крахуна «Челти»', 'Krakhuna “Chelti”', ''],
  [210, 'wine_white_dry', 35, 'გორული მწვანე', 'Горули мцване', 'Goruli Mtsvane', ''],
  [377, 'wine_white_dry', 48, 'ქისი „ბადაგონი“', 'Киси «Бадагони»', 'Kisi “Badagoni”', ''],
  [322, 'wine_white_dry', 91, 'ქისი ქვევრის ბუკეტი „მილდიანი“', 'Киси «Квеври букет» «Милдиани»', 'Kisi Qvevri Bouquet “Mildiani”', ''],
  [522, 'wine_white_dry', 100, 'ქისი ქვევრის „ტერა“ 2023', 'Киси квеври «Тера» 2023', 'Kisi Qvevri “Tera” 2023', ''],
  [493, 'wine_white_dry', 164, 'ქისი ქვევრის „ბადაგონი“', 'Киси квеври «Бадагони»', 'Kisi Qvevri “Badagoni”', ''],
  [323, 'wine_white_dry', 86, 'ხიხვი „მილდიანი“', 'Хихви «Милдиани»', 'Khikhvi “Mildiani”', ''],
  [518, 'wine_white_dry', 100, 'ხიხვი ქვევრის „ტერა“ 2023', 'Хихви квеври «Тера» 2023', 'Khikhvi Qvevri “Tera” 2023', ''],
  [492, 'wine_white_dry', 148, 'ხიხვი ქვევრის „ბადაგონი“', 'Хихви квеври «Бадагони»', 'Khikhvi Qvevri “Badagoni”', ''],
  [523, 'wine_white_dry', 92, 'ქისი-ხიხვი „ტერა“ 2023', 'Киси-Хихви «Тера» 2023', 'Kisi-Khikhvi “Tera” 2023', ''],
  [491, 'wine_white_dry', 74, 'კახური წარჩინებული თეთრი „ბადაგონი“', 'Кахетинское отборное белое «Бадагони»', 'Kakhetian Noble White “Badagoni”', ''],
  [320, 'wine_white_dry', 94, 'შარდონე „მილდიანი“', 'Шардоне «Милдиани»', 'Chardonnay “Mildiani”', ''],
  [490, 'wine_white_dry', 220, 'ალავერდის ტრადიციები „ბადაგონი“', '«Алавердские традиции» «Бадагони»', 'Alaverdi Tradition “Badagoni”', ''],
  // Белое полусухое
  [378, 'wine_white_semidry', 26.5, 'ფიროსმანი „ბადაგონი“', 'Пиросмани «Бадагони»', 'Pirosmani “Badagoni”', ''],
  [307, 'wine_white_semidry', 35, 'ფიროსმანი „მილდიანი“', 'Пиросмани «Милдиани»', 'Pirosmani “Mildiani”', ''],
  [305, 'wine_white_semidry', 59, 'ქისი-მწვანე „მილდიანი“', 'Киси-Мцване «Милдиани»', 'Kisi-Mtsvane “Mildiani”', ''],
  // Белое полусладкое
  [379, 'wine_white_semisweet', 31, 'ალაზნის ველი „ბადაგონი“', 'Алазанская долина «Бадагони»', 'Alazani Valley “Badagoni”', ''],
  [319, 'wine_white_semisweet', 33, 'ალაზნის ველი „მილდიანი“', 'Алазанская долина «Милдиани»', 'Alazani Valley “Mildiani”', ''],
  [380, 'wine_white_semisweet', 58, 'ტვიში „ბადაგონი“', 'Твиши «Бадагони»', 'Tvishi “Badagoni”', ''],
  [321, 'wine_white_semisweet', 98, 'ტვიში პრემიუმი „მილდიანი“', 'Твиши Premium «Милдиани»', 'Tvishi Premium “Mildiani”', ''],
  // Янтарное
  [316, 'wine_amber', 74, 'რქაწითელი ქვევრის ბუკეტი „მილდიანი“', 'Ркацители «Квеври букет» «Милдиани»', 'Rkatsiteli Qvevri Bouquet “Mildiani”', ''],
  [519, 'wine_amber', 92, 'მწვანე „ტერა“ 2021', 'Мцване «Тера» 2021', 'Mtsvane “Tera” 2021', ''],
  // Красное сухое
  [382, 'wine_red_dry', 31.5, 'საფერავი „ბადაგონი“', 'Саперави «Бадагони»', 'Saperavi “Badagoni”', ''],
  [314, 'wine_red_dry', 52, 'საფერავი „მილდიანი“', 'Саперави «Милдиани»', 'Saperavi “Mildiani”', ''],
  [197, 'wine_red_dry', 35, 'საფერავი „ვაზისა“', 'Саперави «Вазиса»', 'Saperavi “Vazisa”', ''],
  [209, 'wine_red_dry', 34, 'საფერავი „ჩელთი“', 'Саперави «Челти»', 'Saperavi “Chelti”', ''],
  [521, 'wine_red_dry', 72, 'საფერავი „ტერა“ 2022', 'Саперави «Тера» 2022', 'Saperavi “Tera” 2022', ''],
  [517, 'wine_red_dry', 100, 'საფერავი „ტერა“ 2020', 'Саперави «Тера» 2020', 'Saperavi “Tera” 2020', '0.75 L'],
  [524, 'wine_red_dry', 88, 'საფერავი ქვევრის „ტერა“ 2022', 'Саперави квеври «Тера» 2022', 'Saperavi Qvevri “Tera” 2022', ''],
  [308, 'wine_red_dry', 95, 'საფერავი ქვევრის ბუკეტი „მილდიანი“', 'Саперави «Квеври букет» «Милдиани»', 'Saperavi Qvevri Bouquet “Mildiani”', ''],
  [489, 'wine_red_dry', 175, 'საფერავი ქვევრის „ბადაგონი“', 'Саперави квеври «Бадагони»', 'Saperavi Qvevri “Badagoni”', ''],
  [324, 'wine_red_dry', 208, 'საფერავი ქვევრის „მილდიანი“', 'Саперави квеври «Милдиани»', 'Saperavi Qvevri “Mildiani”', ''],
  [488, 'wine_red_dry', 608, 'საფერავი რეზერვი „ბადაგონი“', 'Саперави Reserve «Бадагони»', 'Saperavi Reserve “Badagoni”', ''],
  [212, 'wine_red_dry', 25, 'მუკუზანი', 'Мукузани', 'Mukuzani', ''],
  [243, 'wine_red_dry', 25, 'მუკუზანი „რთველისი“', 'Мукузани «Ртвелиси»', 'Mukuzani “Rtvelisi”', ''],
  [383, 'wine_red_dry', 53, 'მუკუზანი „ბადაგონი“', 'Мукузани «Бадагони»', 'Mukuzani “Badagoni”', ''],
  [311, 'wine_red_dry', 72, 'მუკუზანი „მილდიანი“', 'Мукузани «Милдиани»', 'Mukuzani “Mildiani”', ''],
  [516, 'wine_red_dry', 92, 'მუკუზანი „ტერა“ 2021', 'Мукузани «Тера» 2021', 'Mukuzani “Tera” 2021', ''],
  [318, 'wine_red_dry', 99, 'კაბერნე სოვინიონი ქვევრის ბუკეტი „მილდიანი“', 'Каберне Совиньон «Квеври букет» «Милдиани»', 'Cabernet Sauvignon Qvevri Bouquet “Mildiani”', ''],
  [487, 'wine_red_dry', 105, 'კახური წარჩინებული წითელი „ბადაგონი“', 'Кахетинское отборное красное «Бадагони»', 'Kakhetian Noble Red “Badagoni”', ''],
  [317, 'wine_red_dry', 225, 'ალექსანდროული „მილდიანი“', 'Александроули «Милдиани»', 'Aleksandrouli “Mildiani”', ''],
  [486, 'wine_red_dry', 239, 'ალავერდის ტრადიციები „ბადაგონი“', '«Алавердские традиции» «Бадагони»', 'Alaverdi Tradition “Badagoni”', ''],
  // Красное полусухое
  [386, 'wine_red_semidry', 29, 'ფიროსმანი „ბადაგონი“', 'Пиросмани «Бадагони»', 'Pirosmani “Badagoni”', ''],
  [310, 'wine_red_semidry', 32, 'ფიროსმანი „მილდიანი“', 'Пиросмани «Милдиани»', 'Pirosmani “Mildiani”', ''],
  // Красное полусладкое
  [381, 'wine_red_semisweet', 32, 'ალაზნის ველი „ბადაგონი“', 'Алазанская долина «Бадагони»', 'Alazani Valley “Badagoni”', ''],
  [312, 'wine_red_semisweet', 44, 'ალაზნის ველი „მილდიანი“', 'Алазанская долина «Милдиани»', 'Alazani Valley “Mildiani”', ''],
  [201, 'wine_red_semisweet', 35, 'ალაზნის ველი „ქართული ღვინო“', 'Алазанская долина «Грузинское вино»', 'Alazani Valley “Georgian Wine”', ''],
  [199, 'wine_red_semisweet', 35, 'ქინძმარაული „თელიანი ველი“', 'Киндзмараули «Телиани Вели»', 'Kindzmarauli “Teliani Valley”', ''],
  [384, 'wine_red_semisweet', 50, 'ქინძმარაული „ბადაგონი“', 'Киндзмараули «Бадагони»', 'Kindzmarauli “Badagoni”', ''],
  [520, 'wine_red_semisweet', 72, 'ქინძმარაული „ტერა“ 2024', 'Киндзмараули «Тера» 2024', 'Kindzmarauli “Tera” 2024', ''],
  [313, 'wine_red_semisweet', 73, 'ქინძმარაული „მილდიანი“', 'Киндзмараули «Милдиани»', 'Kindzmarauli “Mildiani”', ''],
  [387, 'wine_red_semisweet', 106.5, 'ქინძმარაული პრემიუმი „მილდიანი“', 'Киндзмараули Premium «Милдиани»', 'Kindzmarauli Premium “Mildiani”', ''],
  [198, 'wine_red_semisweet', 50, 'ხვანჭკარა „გონაძე“', 'Хванчкара «Гонадзе»', 'Khvanchkara “Gonadze”', ''],
  [309, 'wine_red_semisweet', 132, 'ხვანჭკარა „მილდიანი“', 'Хванчкара «Милдиани»', 'Khvanchkara “Mildiani”', ''],
  [385, 'wine_red_semisweet', 95, 'ოჯალეში „ბადაგონი“', 'Оджалеши «Бадагони»', 'Ojaleshi “Badagoni”', ''],
  [315, 'wine_red_semisweet', 99, 'ოჯალეში „მილდიანი“', 'Оджалеши «Милдиани»', 'Ojaleshi “Mildiani”', ''],
  [367, 'wine_red_semisweet', 315, 'უსახელოური „მილდიანი“', 'Усахелоури «Милдиани»', 'Usakhelouri “Mildiani”', ''],
  [202, 'wine_red_semisweet', 37, 'პინო', 'Пино', 'Pinot', ''],
  // Вино в бутылках (как в Poster)
  [200, 'wine_bottle', 25, 'ალაზნის ველი „მილდიანი“ (თეთრი ნახევრადტკბილი)', 'Алазанская долина «Милдиани» (белое полусладкое)', 'Alazani Valley “Mildiani” (white semi-sweet)', ''],
  [213, 'wine_bottle', 35, 'ვაზისა', 'Вазиса', 'Vazisa', ''],

  // Чача
  [244, 'chacha_tap', 24, 'ჩამოსასხმელი ჭაჭა', 'Домашняя чача', 'House chacha', '0.5 L'],
  [245, 'chacha_tap', 4, 'ჩამოსასხმელი ჭაჭა', 'Домашняя чача', 'House chacha', '50 ml'],
  [391, 'chacha_tap', 5, 'ჭაჭა „ასკანელი“', 'Чача «Асканели»', 'Chacha “Askaneli”', '50 ml'],
  [443, 'chacha_tap', 5, 'ჭაჭა „კლასიკი“', 'Чача «Классик»', 'Chacha “Classic”', '50 ml'],
  [577, 'chacha_tap', 7, 'ჭაჭა „მარანი“', 'Чача «Марани»', 'Chacha “Marani”', '50 ml'],
  [585, 'chacha_tap', 18, 'ჭაჭა „ჯივიეს“ კლასიკი', 'Чача GVS Classic', 'Chacha GVS Classic', '50 ml'],
  [587, 'chacha_tap', 18, 'ჭაჭა „ჯივიეს“ მუხა', 'Чача GVS в дубе', 'Chacha GVS Oak', '50 ml'],
  [583, 'chacha_tap', 18, 'ჭაჭა „ჯივიეს“ თაფლის', 'Чача GVS медовая', 'Chacha GVS Honey', '50 ml'],
  [589, 'chacha_tap', 38, 'ჭაჭა „შატო მუხრანი“', 'Чача «Шато Мухрани»', 'Chacha “Château Mukhrani”', '50 ml'],
  [214, 'chacha_bottle', 35, 'ჭაჭა „კლასიკი“', 'Чача «Классик»', 'Chacha “Classic”', ''],
  [215, 'chacha_bottle', 35, 'ჭაჭა „მარანი“', 'Чача «Марани»', 'Chacha “Marani”', ''],
  [185, 'chacha_bottle', 40, 'ჭაჭა „ასკანელი“', 'Чача «Асканели»', 'Chacha “Askaneli”', '0.5 L'],
  [217, 'chacha_bottle', 48, 'ჭაჭა „გოლდი“', 'Чача «Голди»', 'Chacha “Goldi”', ''],
  [218, 'chacha_bottle', 60, 'ჭაჭა „ჩელთი“', 'Чача «Челти»', 'Chacha “Chelti”', ''],
  [216, 'chacha_bottle', 85, 'ჭაჭა „რთველისი“', 'Чача «Ртвелиси»', 'Chacha “Rtvelisi”', ''],
  [584, 'chacha_bottle', 185, 'ჭაჭა „ჯივიეს“ კლასიკი', 'Чача GVS Classic', 'Chacha GVS Classic', '0.75 L'],
  [586, 'chacha_bottle', 185, 'ჭაჭა „ჯივიეს“ მუხა', 'Чача GVS в дубе', 'Chacha GVS Oak', '0.75 L'],
  [582, 'chacha_bottle', 185, 'ჭაჭა „ჯივიეს“ თაფლის', 'Чача GVS медовая', 'Chacha GVS Honey', '0.75 L'],
  [588, 'chacha_bottle', 390, 'ჭაჭა „შატო მუხრანი“', 'Чача «Шато Мухрани»', 'Chacha “Château Mukhrani”', '0.75 L'],

  // Коньяк и бренди
  [368, 'brandy', 10, 'ბრენდი 5* „მილდიანი“', 'Бренди 5* «Милдиани»', 'Brandy 5* “Mildiani”', '50 ml'],
  [369, 'brandy', 13, 'ბრენდი 10* „მილდიანი“', 'Бренди 10* «Милдиани»', 'Brandy 10* “Mildiani”', '50 ml'],
  [476, 'brandy', 12, 'სარაჯიშვილი 3*', '«Сараджишвили» 3*', 'Sarajishvili 3*', '50 ml'],
  [566, 'brandy', 64, 'X.O. ბრენდი „მილდიანი“', 'Бренди X.O. «Милдиани»', 'Brandy X.O. “Mildiani”', '50 ml'],
  [365, 'brandy', 68, 'ბრენდი 5* „მილდიანი“', 'Бренди 5* «Милдиани»', 'Brandy 5* “Mildiani”', ''],
  [364, 'brandy', 100, 'ბრენდი 10* „მილდიანი“', 'Бренди 10* «Милдиани»', 'Brandy 10* “Mildiani”', ''],
  [327, 'brandy', 135, 'V.S. ბრენდი „მილდიანი“', 'Бренди V.S. «Милдиани»', 'Brandy V.S. “Mildiani”', '0.7 L'],
  [328, 'brandy', 160, 'V.S.O.P. ბრენდი „მილდიანი“', 'Бренди V.S.O.P. «Милдиани»', 'Brandy V.S.O.P. “Mildiani”', '0.7 L'],
  [565, 'brandy', 697.5, 'X.O. ბრენდი „მილდიანი“', 'Бренди X.O. «Милдиани»', 'Brandy X.O. “Mildiani”', '0.7 L'],
  [184, 'brandy', 60, 'სარაჯიშვილი 3*', '«Сараджишвили» 3*', 'Sarajishvili 3*', '0.5 L'],
  [576, 'brandy', 85, 'სარაჯიშვილი 5*', '«Сараджишвили» 5*', 'Sarajishvili 5*', '0.5 L'],
  [567, 'brandy', 508, 'ჰენესი V.S.', 'Hennessy V.S.', 'Hennessy V.S.', '1 L'],

  // Водка
  [572, 'vodka', 6, 'ჩამოსასხმელი ხილის არაყი', 'Фруктовая водка (разливная)', 'House fruit vodka', '50 ml'],
  [568, 'vodka', 26, 'ჩამოსასხმელი ხილის არაყი', 'Фруктовая водка (разливная)', 'House fruit vodka', '0.5 L'],
  [508, 'vodka', 10, 'დანზკა', 'Danzka', 'Danzka', '50 ml'],
  [561, 'vodka', 10, 'სტოლიჩნაია', 'Столичная', 'Stolichnaya', '50 ml'],
  [363, 'vodka', 12, 'აბსოლუტი', 'Absolut', 'Absolut', '50 ml'],
  [498, 'vodka', 12, 'ფინლანდია', 'Finlandia', 'Finlandia', '50 ml'],
  [573, 'vodka', 32, 'გრეი გუსი', 'Grey Goose', 'Grey Goose', '50 ml'],
  [220, 'vodka', 45, 'კოსკენკორვა', 'Koskenkorva', 'Koskenkorva', '0.5 L'],
  [224, 'vodka', 55, 'ხორტიცა', 'Хортица', 'Khortytsa', '0.5 L'],
  [188, 'vodka', 58, 'სტოლიჩნაია', 'Столичная', 'Stolichnaya', '0.5 L'],
  [186, 'vodka', 75, 'დანზკა', 'Danzka', 'Danzka', '0.5 L'],
  [191, 'vodka', 75, 'ფინლანდია', 'Finlandia', 'Finlandia', '0.5 L'],
  [204, 'vodka', 240, 'გრეი გუსი', 'Grey Goose', 'Grey Goose', '0.5 L'],
  [219, 'vodka', 100, 'კოსკენკორვა', 'Koskenkorva', 'Koskenkorva', '1 L'],
  [223, 'vodka', 105, 'ხორტიცა', 'Хортица', 'Khortytsa', '1 L'],
  [533, 'vodka', 110, 'სტოლიჩნაია', 'Столичная', 'Stolichnaya', '1 L'],
  [187, 'vodka', 112, 'დანზკა', 'Danzka', 'Danzka', '1 L'],
  [192, 'vodka', 135, 'ფინლანდია', 'Finlandia', 'Finlandia', '1 L'],
  [189, 'vodka', 144, 'აბსოლუტი', 'Absolut', 'Absolut', '1 L'],
  [205, 'vodka', 495, 'გრეი გუსი', 'Grey Goose', 'Grey Goose', '1 L'],

  // Виски
  [195, 'whisky', 16, 'ჯეიმსონი', 'Jameson', 'Jameson', '50 ml'],
  [581, 'whisky', 17, 'ჩივას რიგალი', 'Chivas Regal', 'Chivas Regal', '50 ml'],
  [193, 'whisky', 18, 'ჯეკ დენიელსი', "Jack Daniel's", "Jack Daniel's", '50 ml'],
  [407, 'whisky', 22, 'გლენფიდიში', 'Glenfiddich', 'Glenfiddich', '50 ml'],
  [406, 'whisky', 25, 'გლენმორანჟი', 'Glenmorangie', 'Glenmorangie', '50 ml'],
  [194, 'whisky', 160, 'ჯეკ დენიელსი', "Jack Daniel's", "Jack Daniel's", '0.7 L'],
  [414, 'whisky', 230, 'ჯეიმსონი', 'Jameson', 'Jameson', '0.7 L'],
  [196, 'whisky', 280, 'ჯეიმსონი', 'Jameson', 'Jameson', '1 L'],
  [580, 'whisky', 300, 'ჩივას რიგალი', 'Chivas Regal', 'Chivas Regal', '1 L'],
  [394, 'whisky', 350, 'გლენმორანჟი', 'Glenmorangie', 'Glenmorangie', ''],
  [393, 'whisky', 420, 'გლენფიდიში', 'Glenfiddich', 'Glenfiddich', ''],
  // Ром, текила, джин
  [496, 'rum_tequila', 13, 'ბიფიტერი', 'Beefeater', 'Beefeater gin', '50 ml'],
  [403, 'rum_tequila', 14, 'ტეკილა ოლმეკა სილვერი', 'Текила Olmeca Silver', 'Olmeca Silver tequila', '50 ml'],
  [404, 'rum_tequila', 14, 'ტეკილა ოლმეკა გოლდი', 'Текила Olmeca Gold', 'Olmeca Gold tequila', '50 ml'],
  [399, 'rum_tequila', 18, 'კაპიტანი მორგანი', 'Captain Morgan', 'Captain Morgan', '50 ml'],
  [562, 'rum_tequila', 120, 'ტეკილა ოლმეკა სილვერი', 'Текила Olmeca Silver', 'Olmeca Silver tequila', '0.5 L'],
  [483, 'rum_tequila', 227, 'ტეკილა ოლმეკა სილვერი', 'Текила Olmeca Silver', 'Olmeca Silver tequila', '1 L'],
  [392, 'rum_tequila', 255, 'კაპიტანი მორგანი', 'Captain Morgan', 'Captain Morgan', ''],
  // Ликёры и вермуты
  [477, 'liqueurs', 10, 'იაგერმაისტერი', 'Jägermeister', 'Jägermeister', '50 ml'],
  [578, 'liqueurs', 10, 'ბეილისი', 'Baileys', 'Baileys', '50 ml'],
  [537, 'liqueurs', 11, 'მალიბუ', 'Malibu', 'Malibu', '50 ml'],
  [534, 'liqueurs', 14, 'მარტინი ბიანკო', 'Martini Bianco', 'Martini Bianco', '100 ml'],
  [395, 'liqueurs', 105, 'მარტინი ბიანკო', 'Martini Bianco', 'Martini Bianco', ''],
  [396, 'liqueurs', 105, 'მარტინი როსო', 'Martini Rosso', 'Martini Rosso', ''],

  // Пиво
  [232, 'beer', 7.5, 'ზედაზენი (ჩამოსასხმელი)', 'Зедазени (разливное)', 'Zedazeni (draught)', '0.5 L'],
  [231, 'beer', 12.9, 'ჰაინეკენი (ჩამოსასხმელი)', 'Heineken (разливное)', 'Heineken (draught)', '0.5 L'],
  [446, 'beer', 16, 'კრომბახერი (გაუფილტრავი)', 'Krombacher нефильтрованное', 'Krombacher unfiltered', '0.4 L'],
  [530, 'beer', 16, 'კრომბახერი (ბოთლი)', 'Krombacher (бутылка)', 'Krombacher (bottle)', ''],
  [353, 'beer', 16.5, 'პრიმატორი ვაიცენი (გაუფილტრავი)', 'Primátor Weizen нефильтрованное', 'Primátor Weizen unfiltered', '0.5 L'],
  [354, 'beer', 16.5, 'პრიმატორი IPA (გაუფილტრავი)', 'Primátor IPA нефильтрованное', 'Primátor IPA unfiltered', '0.5 L'],
  [359, 'beer', 19, 'არკობროი მოზერ ლიზლი', 'Arcobräu Mooser Liesl', 'Arcobräu Mooser Liesl', '0.5 L'],
  [357, 'beer', 19, 'გულდენ დრაკი ქვადრუპელი', 'Gulden Draak Quadruple', 'Gulden Draak Quadruple', '0.33 L'],
  [358, 'beer', 19, 'გულდენ დრაკი იმპერიალ სტაუტი', 'Gulden Draak Imperial Stout', 'Gulden Draak Imperial Stout', '0.33 L'],
  [352, 'beer', 20.6, 'გრევენშტაინერი', 'Grevensteiner', 'Grevensteiner', '0.5 L'],
  [355, 'beer', 20.6, 'აინგერი ჰელი', 'Ayinger Hell', 'Ayinger Hell', '0.5 L'],
  [356, 'beer', 20.6, 'აინგერი ბრაუ-ვაისი', 'Ayinger Bräu-Weisse', 'Ayinger Bräu-Weisse', '0.5 L'],
  [563, 'beer', 14.9, 'ჰაინეკენი უალკოჰოლო', 'Heineken безалкогольное', 'Heineken 0.0 (non-alcoholic)', '0.33 L'],

  // Коктейли
  [166, 'cocktails', 25, 'ლურჯი ქალაქი', '«Голубой город»', 'Blue City', ''],
  [413, 'cocktails', 28, 'მარწყვიტო', 'Клубничный мохито', 'Strawberry mojito', ''],
  [161, 'cocktails', 30, 'აპეროლ შპრიცი', 'Апероль шприц', 'Aperol Spritz', ''],
  [162, 'cocktails', 25, 'აპეროლ საუერი', 'Апероль сауэр', 'Aperol Sour', ''],
  [175, 'cocktails', 25, 'ესპრესო მარტინი', 'Эспрессо мартини', 'Espresso Martini', ''],
  [159, 'cocktails', 25, 'ნეგრონი', 'Негрони', 'Negroni', ''],
  [176, 'cocktails', 25, 'კოსმოპოლიტენი', 'Космополитен', 'Cosmopolitan', ''],
  [177, 'cocktails', 25, 'მარგარიტა', 'Маргарита', 'Margarita', ''],
  [171, 'cocktails', 25, 'მოჰიტო', 'Мохито', 'Mojito', ''],
  [164, 'cocktails', 25, 'პინაკოლადა', 'Пина колада', 'Piña Colada', ''],
  [179, 'cocktails', 25, 'კუბა ლიბრე', 'Куба либре', 'Cuba Libre', ''],
  [170, 'cocktails', 25, 'ჯინ-ტონიკი', 'Джин-тоник', 'Gin & Tonic', ''],
  [174, 'cocktails', 30, 'ჯინ-ტონიკი ჰენდრიქსი', "Джин-тоник Hendrick's", "Hendrick's Gin & Tonic", ''],
  [178, 'cocktails', 30, 'ვისკი საუერი', 'Виски сауэр', 'Whiskey Sour', ''],
  [180, 'cocktails', 28, 'ნიუ-იორკ საუერი', 'Нью-Йорк сауэр', 'New York Sour', ''],
  [167, 'cocktails', 30, 'მაი ტაი', 'Май тай', 'Mai Tai', ''],
  [163, 'cocktails', 35, 'ადიოსი', 'Адьос', 'Adios', ''],
  [169, 'cocktails', 35, 'ლონგ აილენდ აის თი', 'Лонг-Айленд айс ти', 'Long Island Iced Tea', ''],
  [168, 'cocktails', 40, 'ლონგ აილენდ ენერჯი', 'Лонг-Айленд энерджи', 'Long Island Energy', ''],
  [247, 'cocktails', 18, 'ტეკილა სანრაიზი', 'Текила санрайз', 'Tequila Sunrise', ''],
  [172, 'cocktails', 18, 'მოჰიტო (უალკოჰოლო)', 'Мохито безалкогольный', 'Virgin Mojito', ''],
  [165, 'cocktails', 18, 'პინაკოლადა (უალკოჰოლო)', 'Пина колада безалкогольная', 'Virgin Piña Colada', ''],

  // Кофе и чай
  [140, 'coffee', 7, 'ესპრესო', 'Эспрессо', 'Espresso', ''],
  [139, 'coffee', 8, 'ამერიკანო', 'Американо', 'Americano', ''],
  [141, 'coffee', 12, 'კაპუჩინო', 'Капучино', 'Cappuccino', ''],
  [142, 'coffee', 14, 'ლატე', 'Латте', 'Latte', ''],
  [143, 'coffee', 5, 'ნალექიანი ყავა', 'Кофе по-восточному', 'Turkish coffee', ''],
  [144, 'coffee', 10, 'ცივი ყავა', 'Холодный кофе', 'Iced coffee', ''],
  [145, 'coffee', 15, 'ცივი ყავა ნაყინით', 'Холодный кофе с мороженым', 'Iced coffee with ice cream', ''],
  [569, 'coffee', 10, 'ესპრესო-ტონიკი', 'Эспрессо-тоник', 'Espresso tonic', ''],
  [227, 'coffee', 8, 'შავი ჩაი', 'Чёрный чай', 'Black tea', ''],
  [226, 'coffee', 8, 'მწვანე ჩაი', 'Зелёный чай', 'Green tea', ''],
  [225, 'coffee', 8, 'ხილის ჩაი', 'Фруктовый чай', 'Fruit tea', ''],
  [146, 'coffee', 15, 'დასაყენებელი ჩაი (ჩაიდანი)', 'Заварной чай (чайник)', 'Brewed tea (pot)', ''],
  [290, 'coffee', 2, 'რძე', 'Молоко', 'Milk', ''],
  [293, 'coffee', 2, 'ლიმონი', 'Лимон', 'Lemon', ''],

  // Лимонады, соки, вода
  [405, 'soft', 16, 'საფირმო ლიმონათი', 'Фирменный лимонад', 'Signature lemonade', '1 glass'],
  [148, 'soft', 24.9, 'საფირმო ლიმონათი', 'Фирменный лимонад', 'Signature lemonade', '1 L'],
  [299, 'soft', 4.9, 'ლიმონათი „ზედაზენი“', 'Лимонад «Зедазени»', 'Zedazeni lemonade', ''],
  [246, 'soft', 5, 'ნატურალური წვენი', 'Натуральный сок', 'Natural juice', '250 ml'],
  [149, 'soft', 16, 'ნატურალური წვენი', 'Натуральный сок', 'Natural juice', '1 L'],
  [151, 'soft', 5, 'კოკა-კოლა', 'Coca-Cola', 'Coca-Cola', ''],
  [153, 'soft', 5, 'კოკა-კოლა ზერო', 'Coca-Cola Zero', 'Coca-Cola Zero', ''],
  [571, 'soft', 7, 'ტონიკი', 'Тоник', 'Tonic water', ''],
  [343, 'soft', 4, 'წყალი „ჯეო ნატურა“', 'Вода «Geo Natura»', 'Geo Natura water', ''],
  [351, 'soft', 4, 'ნაბეღლავი', 'Набеглави', 'Nabeghlavi mineral water', ''],
  [570, 'soft', 10, 'ენერგეტიკული XL', 'Энергетик XL', 'Energy drink XL', '0.33 L'],
  [155, 'soft', 11, 'ენერგეტიკული ორიგინალი', 'Энергетик Original', 'Energy drink Original', ''],
  [401, 'soft', 11, 'ენერგეტიკული ციტრუსის', 'Энергетик цитрусовый', 'Citrus energy drink', ''],
  // Милкшейки
  [182, 'milkshakes', 25, 'ვანილის მილქშეიქი', 'Ванильный милкшейк', 'Vanilla milkshake', ''],
  [181, 'milkshakes', 25, 'კენკრის მილქშეიქი', 'Ягодный милкшейк', 'Berry milkshake', ''],
];
